// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: oneofs.proto

package cases

import (
	_ "github.com/protoconf/proto-validate-reflect/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestOneOfMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Val bool `protobuf:"varint,1,opt,name=val,proto3" json:"val,omitempty"`
}

func (x *TestOneOfMsg) Reset() {
	*x = TestOneOfMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oneofs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestOneOfMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestOneOfMsg) ProtoMessage() {}

func (x *TestOneOfMsg) ProtoReflect() protoreflect.Message {
	mi := &file_oneofs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestOneOfMsg.ProtoReflect.Descriptor instead.
func (*TestOneOfMsg) Descriptor() ([]byte, []int) {
	return file_oneofs_proto_rawDescGZIP(), []int{0}
}

func (x *TestOneOfMsg) GetVal() bool {
	if x != nil {
		return x.Val
	}
	return false
}

type OneOfNone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to O:
	//	*OneOfNone_X
	//	*OneOfNone_Y
	O isOneOfNone_O `protobuf_oneof:"o"`
}

func (x *OneOfNone) Reset() {
	*x = OneOfNone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oneofs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OneOfNone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneOfNone) ProtoMessage() {}

func (x *OneOfNone) ProtoReflect() protoreflect.Message {
	mi := &file_oneofs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneOfNone.ProtoReflect.Descriptor instead.
func (*OneOfNone) Descriptor() ([]byte, []int) {
	return file_oneofs_proto_rawDescGZIP(), []int{1}
}

func (m *OneOfNone) GetO() isOneOfNone_O {
	if m != nil {
		return m.O
	}
	return nil
}

func (x *OneOfNone) GetX() string {
	if x, ok := x.GetO().(*OneOfNone_X); ok {
		return x.X
	}
	return ""
}

func (x *OneOfNone) GetY() int32 {
	if x, ok := x.GetO().(*OneOfNone_Y); ok {
		return x.Y
	}
	return 0
}

type isOneOfNone_O interface {
	isOneOfNone_O()
}

type OneOfNone_X struct {
	X string `protobuf:"bytes,1,opt,name=x,proto3,oneof"`
}

type OneOfNone_Y struct {
	Y int32 `protobuf:"varint,2,opt,name=y,proto3,oneof"`
}

func (*OneOfNone_X) isOneOfNone_O() {}

func (*OneOfNone_Y) isOneOfNone_O() {}

type OneOf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to O:
	//	*OneOf_X
	//	*OneOf_Y
	//	*OneOf_Z
	O isOneOf_O `protobuf_oneof:"o"`
}

func (x *OneOf) Reset() {
	*x = OneOf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oneofs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OneOf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneOf) ProtoMessage() {}

func (x *OneOf) ProtoReflect() protoreflect.Message {
	mi := &file_oneofs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneOf.ProtoReflect.Descriptor instead.
func (*OneOf) Descriptor() ([]byte, []int) {
	return file_oneofs_proto_rawDescGZIP(), []int{2}
}

func (m *OneOf) GetO() isOneOf_O {
	if m != nil {
		return m.O
	}
	return nil
}

func (x *OneOf) GetX() string {
	if x, ok := x.GetO().(*OneOf_X); ok {
		return x.X
	}
	return ""
}

func (x *OneOf) GetY() int32 {
	if x, ok := x.GetO().(*OneOf_Y); ok {
		return x.Y
	}
	return 0
}

func (x *OneOf) GetZ() *TestOneOfMsg {
	if x, ok := x.GetO().(*OneOf_Z); ok {
		return x.Z
	}
	return nil
}

type isOneOf_O interface {
	isOneOf_O()
}

type OneOf_X struct {
	X string `protobuf:"bytes,1,opt,name=x,proto3,oneof"`
}

type OneOf_Y struct {
	Y int32 `protobuf:"varint,2,opt,name=y,proto3,oneof"`
}

type OneOf_Z struct {
	Z *TestOneOfMsg `protobuf:"bytes,3,opt,name=z,proto3,oneof"`
}

func (*OneOf_X) isOneOf_O() {}

func (*OneOf_Y) isOneOf_O() {}

func (*OneOf_Z) isOneOf_O() {}

type OneOfRequired struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to O:
	//	*OneOfRequired_X
	//	*OneOfRequired_Y
	//	*OneOfRequired_NameWithUnderscores
	//	*OneOfRequired_UnderAnd_1Number
	O isOneOfRequired_O `protobuf_oneof:"o"`
}

func (x *OneOfRequired) Reset() {
	*x = OneOfRequired{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oneofs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OneOfRequired) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneOfRequired) ProtoMessage() {}

func (x *OneOfRequired) ProtoReflect() protoreflect.Message {
	mi := &file_oneofs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneOfRequired.ProtoReflect.Descriptor instead.
func (*OneOfRequired) Descriptor() ([]byte, []int) {
	return file_oneofs_proto_rawDescGZIP(), []int{3}
}

func (m *OneOfRequired) GetO() isOneOfRequired_O {
	if m != nil {
		return m.O
	}
	return nil
}

func (x *OneOfRequired) GetX() string {
	if x, ok := x.GetO().(*OneOfRequired_X); ok {
		return x.X
	}
	return ""
}

func (x *OneOfRequired) GetY() int32 {
	if x, ok := x.GetO().(*OneOfRequired_Y); ok {
		return x.Y
	}
	return 0
}

func (x *OneOfRequired) GetNameWithUnderscores() int32 {
	if x, ok := x.GetO().(*OneOfRequired_NameWithUnderscores); ok {
		return x.NameWithUnderscores
	}
	return 0
}

func (x *OneOfRequired) GetUnderAnd_1Number() int32 {
	if x, ok := x.GetO().(*OneOfRequired_UnderAnd_1Number); ok {
		return x.UnderAnd_1Number
	}
	return 0
}

type isOneOfRequired_O interface {
	isOneOfRequired_O()
}

type OneOfRequired_X struct {
	X string `protobuf:"bytes,1,opt,name=x,proto3,oneof"`
}

type OneOfRequired_Y struct {
	Y int32 `protobuf:"varint,2,opt,name=y,proto3,oneof"`
}

type OneOfRequired_NameWithUnderscores struct {
	NameWithUnderscores int32 `protobuf:"varint,3,opt,name=name_with_underscores,json=nameWithUnderscores,proto3,oneof"`
}

type OneOfRequired_UnderAnd_1Number struct {
	UnderAnd_1Number int32 `protobuf:"varint,4,opt,name=under_and_1_number,json=underAnd1Number,proto3,oneof"`
}

func (*OneOfRequired_X) isOneOfRequired_O() {}

func (*OneOfRequired_Y) isOneOfRequired_O() {}

func (*OneOfRequired_NameWithUnderscores) isOneOfRequired_O() {}

func (*OneOfRequired_UnderAnd_1Number) isOneOfRequired_O() {}

var File_oneofs_proto protoreflect.FileDescriptor

var file_oneofs_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13,
	0x74, 0x65, 0x73, 0x74, 0x73, 0x2e, 0x68, 0x61, 0x72, 0x6e, 0x65, 0x73, 0x73, 0x2e, 0x63, 0x61,
	0x73, 0x65, 0x73, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x29, 0x0a, 0x0c,
	0x54, 0x65, 0x73, 0x74, 0x4f, 0x6e, 0x65, 0x4f, 0x66, 0x4d, 0x73, 0x67, 0x12, 0x19, 0x0a, 0x03,
	0x76, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x6a, 0x02,
	0x08, 0x01, 0x52, 0x03, 0x76, 0x61, 0x6c, 0x22, 0x30, 0x0a, 0x09, 0x4f, 0x6e, 0x65, 0x4f, 0x66,
	0x4e, 0x6f, 0x6e, 0x65, 0x12, 0x0e, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x01, 0x78, 0x12, 0x0e, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x48,
	0x00, 0x52, 0x01, 0x79, 0x42, 0x03, 0x0a, 0x01, 0x6f, 0x22, 0x74, 0x0a, 0x05, 0x4f, 0x6e, 0x65,
	0x4f, 0x66, 0x12, 0x1a, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0a, 0xfa,
	0x42, 0x07, 0x72, 0x05, 0x3a, 0x03, 0x66, 0x6f, 0x6f, 0x48, 0x00, 0x52, 0x01, 0x78, 0x12, 0x17,
	0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x1a, 0x02,
	0x20, 0x00, 0x48, 0x00, 0x52, 0x01, 0x79, 0x12, 0x31, 0x0a, 0x01, 0x7a, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x21, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2e, 0x68, 0x61, 0x72, 0x6e, 0x65,
	0x73, 0x73, 0x2e, 0x63, 0x61, 0x73, 0x65, 0x73, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x4f, 0x6e, 0x65,
	0x4f, 0x66, 0x4d, 0x73, 0x67, 0x48, 0x00, 0x52, 0x01, 0x7a, 0x42, 0x03, 0x0a, 0x01, 0x6f, 0x22,
	0x9e, 0x01, 0x0a, 0x0d, 0x4f, 0x6e, 0x65, 0x4f, 0x66, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65,
	0x64, 0x12, 0x0e, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x01,
	0x78, 0x12, 0x0e, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x01,
	0x79, 0x12, 0x34, 0x0a, 0x15, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x77, 0x69, 0x74, 0x68, 0x5f, 0x75,
	0x6e, 0x64, 0x65, 0x72, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x48, 0x00, 0x52, 0x13, 0x6e, 0x61, 0x6d, 0x65, 0x57, 0x69, 0x74, 0x68, 0x55, 0x6e, 0x64, 0x65,
	0x72, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x12, 0x2d, 0x0a, 0x12, 0x75, 0x6e, 0x64, 0x65, 0x72,
	0x5f, 0x61, 0x6e, 0x64, 0x5f, 0x31, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x0f, 0x75, 0x6e, 0x64, 0x65, 0x72, 0x41, 0x6e, 0x64, 0x31,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x42, 0x08, 0x0a, 0x01, 0x6f, 0x12, 0x03, 0xf8, 0x42, 0x01,
	0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6e, 0x66, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2d, 0x72, 0x65, 0x66, 0x6c, 0x65, 0x63, 0x74, 0x2f,
	0x63, 0x61, 0x73, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_oneofs_proto_rawDescOnce sync.Once
	file_oneofs_proto_rawDescData = file_oneofs_proto_rawDesc
)

func file_oneofs_proto_rawDescGZIP() []byte {
	file_oneofs_proto_rawDescOnce.Do(func() {
		file_oneofs_proto_rawDescData = protoimpl.X.CompressGZIP(file_oneofs_proto_rawDescData)
	})
	return file_oneofs_proto_rawDescData
}

var file_oneofs_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_oneofs_proto_goTypes = []interface{}{
	(*TestOneOfMsg)(nil),  // 0: tests.harness.cases.TestOneOfMsg
	(*OneOfNone)(nil),     // 1: tests.harness.cases.OneOfNone
	(*OneOf)(nil),         // 2: tests.harness.cases.OneOf
	(*OneOfRequired)(nil), // 3: tests.harness.cases.OneOfRequired
}
var file_oneofs_proto_depIdxs = []int32{
	0, // 0: tests.harness.cases.OneOf.z:type_name -> tests.harness.cases.TestOneOfMsg
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_oneofs_proto_init() }
func file_oneofs_proto_init() {
	if File_oneofs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_oneofs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestOneOfMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oneofs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OneOfNone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oneofs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OneOf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oneofs_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OneOfRequired); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_oneofs_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*OneOfNone_X)(nil),
		(*OneOfNone_Y)(nil),
	}
	file_oneofs_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*OneOf_X)(nil),
		(*OneOf_Y)(nil),
		(*OneOf_Z)(nil),
	}
	file_oneofs_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*OneOfRequired_X)(nil),
		(*OneOfRequired_Y)(nil),
		(*OneOfRequired_NameWithUnderscores)(nil),
		(*OneOfRequired_UnderAnd_1Number)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_oneofs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_oneofs_proto_goTypes,
		DependencyIndexes: file_oneofs_proto_depIdxs,
		MessageInfos:      file_oneofs_proto_msgTypes,
	}.Build()
	File_oneofs_proto = out.File
	file_oneofs_proto_rawDesc = nil
	file_oneofs_proto_goTypes = nil
	file_oneofs_proto_depIdxs = nil
}
